apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-client
spec:
  selector:
    matchLabels:
      run: datagen-client
  replicas: 1
  template:
    metadata:
      labels:
        run: datagen-client
    spec:
      containers:
      - name: datagen-client
        image: datagen-client
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
