apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen
spec:
  selector:
    matchLabels:
      run: datagen
  replicas: 1
  template:
    metadata:
      labels:
        run: datagen
    spec:
      containers:
      - name: datagen
        image: datagen
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
